"""
Reverse Sampling & Digit Generation for Vision DDPM.

Loads a trained SmallUNet model, starts from pure Gaussian noise
x_T ~ N(0, I), and runs the reverse diffusion loop to generate:
1. A multi-digit showcase grid (e.g. 32 novel synthetic digits).
2. A reverse denoising step-by-step strip showing digits emerging from static.
"""

import os
import argparse
import torch
import matplotlib.pyplot as plt

from unet import SmallUNet
from diffusion import GaussianDiffusionImage


def sample_digits(
    checkpoint_path: str = "checkpoints/mnist_ddpm_mnist.pt",
    num_samples: int = 32,
    output_dir: str = "outputs"
):
    os.makedirs(output_dir, exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Checkpoint not found at: {checkpoint_path}. Run train.py first!")

    print(f"[*] Loading checkpoint from: {checkpoint_path}")
    ckpt = torch.load(checkpoint_path, map_location=device)
    dataset_name = ckpt.get("dataset_name", "mnist")
    timesteps = ckpt.get("timesteps", 300)
    base_channels = ckpt.get("base_channels", 32)

    # 1. Instantiate model & scheduler
    model = SmallUNet(in_channels=1, base_channels=base_channels, time_emb_dim=64).to(device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    diffusion = GaussianDiffusionImage(num_timesteps=timesteps, beta_schedule="linear", device=device)

    print(f"[*] Generating {num_samples} novel images via reverse diffusion on {device}...")

    # 2. Generate samples with full trajectory recording
    final_images, trajectory = diffusion.sample(
        model=model,
        shape=(num_samples, 1, 28, 28),
        return_trajectory=True
    )
    # Denormalize from [-1, 1] to [0, 1]
    final_vis = (final_images * 0.5 + 0.5).cpu().numpy()

    # 3. Create Sample Grid (e.g., 4 rows x 8 cols)
    cols = 8
    rows = max(1, num_samples // cols)
    fig, axes = plt.subplots(rows, cols, figsize=(cols * 1.5, rows * 1.5))
    fig.patch.set_facecolor('#0f172a')

    for idx in range(rows * cols):
        r, c = idx // cols, idx % cols
        ax = axes[r, c] if rows > 1 else axes[c]
        ax.set_facecolor('#0f172a')
        ax.imshow(final_vis[idx, 0], cmap='gray', vmin=0, vmax=1)
        ax.axis('off')

    plt.suptitle(
        f"Synthetic {dataset_name.upper()} Digits Generated by DDPM\n(Sampled from pure Gaussian noise)",
        color='#f8fafc',
        fontsize=14,
        y=0.98
    )

    grid_path = os.path.join(output_dir, f"generated_digits_{dataset_name}.png")
    plt.savefig(grid_path, dpi=200, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()
    print(f"[OK] Saved generated digits grid to: {grid_path}")

    # 4. Create Reverse Denoising Progression Strip for 4 digits
    num_strip = min(4, num_samples)
    eval_indices = [0, int(timesteps * 0.25), int(timesteps * 0.5), int(timesteps * 0.75), int(timesteps * 0.9), timesteps]
    step_labels = ["t = T\n(Noise)", f"t = {int(timesteps*0.75)}", f"t = {int(timesteps*0.5)}", f"t = {int(timesteps*0.25)}", f"t = {int(timesteps*0.1)}", "t = 0\n(Final)"]

    fig, axes = plt.subplots(num_strip, len(eval_indices), figsize=(14, 2.3 * num_strip))
    fig.patch.set_facecolor('#0f172a')

    for col_idx, traj_idx in enumerate(eval_indices):
        frame = trajectory[traj_idx][:num_strip]
        frame_vis = (torch.clamp(frame, -1.0, 1.0) * 0.5 + 0.5).cpu().numpy()

        for row_idx in range(num_strip):
            ax = axes[row_idx, col_idx] if num_strip > 1 else axes[col_idx]
            ax.set_facecolor('#0f172a')
            ax.imshow(frame_vis[row_idx, 0], cmap='gray', vmin=0, vmax=1)
            ax.axis('off')

            if row_idx == 0:
                ax.set_title(step_labels[col_idx], color='#f8fafc', fontsize=11, pad=8)

    plt.suptitle(
        f"DDPM Reverse Denoising Trajectory p_theta(x_{{t-1}} | x_t) on {dataset_name.upper()}\nHandwritten strokes crystallizing from pixel noise",
        color='#f8fafc',
        fontsize=13,
        y=0.99
    )

    strip_path = os.path.join(output_dir, f"reverse_denoising_{dataset_name}.png")
    plt.savefig(strip_path, dpi=200, bbox_inches='tight', facecolor=fig.get_facecolor())
    plt.close()
    print(f"[OK] Saved reverse denoising trajectory strip to: {strip_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate digit samples from trained Vision DDPM.")
    parser.add_argument("--checkpoint", type=str, default="checkpoints/mnist_ddpm_mnist.pt")
    parser.add_argument("--samples", type=int, default=32)
    parser.add_argument("--output_dir", type=str, default="outputs")
    args = parser.parse_args()

    sample_digits(
        checkpoint_path=args.checkpoint,
        num_samples=args.samples,
        output_dir=args.output_dir
    )
